### ISSUE TITLE
spglib 2.4.0 requires typing-extensions, which is not installed.

### ISSUE THREAD

**Issue by atztogo** [conda-forge/spglib-feedstock#112]
### Comment:

I have a question. I appreciate if somebody could give me answer (@LecrisUT).

I encountered build failure of phono3py conda-forge package as shown at the bottom of the following link,

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=918617&view=logs&jobId=4f922444-fdfe-5dcf-b824-02f86439ef14&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=937c195f-508d-5135-dc9f-d4b5730df0f7

phono3py depends on spglib. Should spglib conda forge package for python<3.9 install typing-extensions automatically or it is responsibility of the depending package like phono3py?

**Comment by LecrisUT** [comment]
Good catch, yes it should. I need to check why it doesn't pick it up automatically from `pyproject.toml`

In the last PR: https://github.com/conda-forge/spglib-feedstock/pull/111 it does mention some requirements that are not in `meta.yaml`, but we don't actually use any of those, and `pytest` and `pyyaml` are in the test dependencies
